name: .NET Windows Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup MSBuild path
      uses: microsoft/setup-msbuild@v1.0.2 # This action sets up MSBuild for the workflow
    - name: Restore dependencies
      run: nuget restore WindowsFormsApp1.sln # Replace YourSolution.sln with your solution file name
    - name: Build
      run: msbuild /p:Configuration=Release WindowsFormsApp1.sln # Replace YourSolution.sln with your solution file name
    - name: Test
      run: |
        # Run your tests here, replace this comment with the actual command to run tests
        # For example:
        dotnet test WindowsFormsApp1/WindowsFormsApp1.csproj
